-- SQLite
SELECT PAREIGOS FROM DARBUOTOJAI WHERE VARDAS = "Giedrius";

SELECT * FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1986-09-19"

SELECT VARDAS FROM DARBUOTOJAI WHERE PAVARDĖ = "Sabutis";

SELECT VARDAS, PAVARDĖ FROM DARBUOTOJAI WHERE PAREIGOS = "Programuotojas" AND SKYRIUS_PAVADINIMAS = "Gamybos";

INSERT INTO DARBUOTOJAI VALUES ("Antanas", "Marmalas", "1984-09-11", "Vadovas", "Pardavimu");

INSERT INTO DARBUOTOJAI (VARDAS, "PAVARDĖ", GIMIMO_DATA) VALUES ("Domas", "Varnas", "1977-09-14");

UPDATE DARBUOTOJAI SET PAREIGOS = "Programuotojas", SKYRIUS_PAVADINIMAS = "Gamybos" WHERE VARDAS = "Domas" AND PAVARDĖ = "Varnas";

DELETE FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1984-09-11";

INSERT INTO DARBUOTOJAI VALUES ("Antanas", "Antanaitis", "1997-10-10", "Programuotojas", "Gamybos");
INSERT INTO DARBUOTOJAI VALUES("Mantas", "Antanaitis", "2002-03-14", "Programuotojas", "Gamybos");

UPDATE DARBUOTOJAI SET PAREIGOS = "Testuotojas" WHERE PAVARDĖ = "Antanaitis";

SELECT count() FROM DARBUOTOJAI WHERE PAREIGOS = "Testuotojas";

SELECT * from DARBUOTOJAI; 

